//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaBD_Misa
{
    using System;
    using System.Collections.Generic;
    
    public partial class puertas
    {
        public string door_id { get; set; }
        public string doorName { get; set; }
        public string doorStatus { get; set; }
        public string doorLocation { get; set; }
    }
}
