//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaBD_Misa
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string user_id { get; set; }
        public string username { get; set; }
        public string user_firstName { get; set; }
        public string user_lastName { get; set; }
    }
}
